### ISSUE TITLE
schematics

### ISSUE THREAD

**Issue by joopvdl** [matthewfriedrichs/DarkAliasManual#1]
First I want to say Dark Alias is a wonderful oscillator. I am having fun experimenting with it, and with the examples.
Having said that, I find it hard to understand what exactly is going on. 

1. You say all is coming from one sine wave. Indeed, I hear that when the osc is in its initial state. But when I move the LP fader up, I hear harmonics entering. Where do these come from? Not all harmonics are present. How many are there?
2. If I understand correctly, all ratio knobs are normalized to the sliders underneath them, through attenuverters. Ratio 1 is also normalized to the fm input. Am I correct?
3. If the answer to 2. is correct, then what's the difference between the sliders and the attenuverters? For instance, if I set ratio 2 to a certain value, and I set the fold slider to 1, the result is different from when I set the fold attenuverter to 1.

**Comment by matthewfriedrichs** [comment]
I am glad to hear that you are enjoying the oscillator. It will be a while before even I know what all it can do, but I can answer these questions. 

First let's talk about points 2 and 3. 
The RATIO knobs set the rate of oscillation of the 4 sine wave operators. The operators are sine waves that are RATIOS of the main V/Oct pitch input that oscillate between -5V and 5V.
You can type in common ratios in semitones using the tooltips. For example, a ratio of 2:1 would be 12 semitones. You can also generate inharmonic ratios for a wider palette of sounds.
This is why you get a different wavefolder sound when you introduce operator 2 to the FOLD parameter with the attenuverter. You are sweeping the wavefolder at audio rate. 
Yes, Operator 1 is normalized to the FM CV input as well as the FM AUDIO input. You can use this to "bend" the FM signal. I have found that when you use an unused operator to sync Dark Alias to itself that you can use these two parameters to generate common wave folding patterns.
You always have the 4 operators available on output jacks below the ratio knobs.

Now for point 1. The oscillator is made up of only sine waves. There are 8 harmonics, and 4 operators for a total of 12 sine waves. How does the algorithm work? It all kind of happens in one step at the same time, so it took me a while to think of the best way to imagine the "order of operations".
There are 8 harmonics. 
First, all 8 harmonics are frequency modulated. 
Second, the low pass filter decides what harmonics get used in the rest of the algorithm from 1 harmonic to all 8. 
Third, the comb filter shuffles the passed harmonics around. 
Fourth, a wavefolder is applied to each harmonic.
Finally, all 8 harmonics are mixed into the final output.
None of these 4 transformations affect the 4 sinewave operators.

I hope that clears a few things up for you. If it didn't, please let me know.

**Comment by joopvdl** [comment]
Thanks. It took me some time to understand your answer, but it makes sense now. Still puzzling at the examples you provided, especially the supersaw.
Am I right in concluding that the operator sine waves cannot be mixed into the main output?

**Comment by matthewfriedrichs** [comment]
That is correct. The operator sine waves are not mixed into the main output. You can use an external mixer to do that, and turn the oscillator into a more traditional additive oscillator with 4 harmonics.

**Comment by joopvdl** [comment]
Hey, hadn't thought of that 🙄
